### ISSUE TITLE
/request Page

### ISSUE THREAD

**Issue by birdsong** [CityOfPhiladelphia/slash-data#12]
- Remove Resources Box
- Extract Language from Right To Know Procedure PDF and link to PDF form with only the two relevant pages of the RTK PDF

@gsf

**Comment by gsf** [comment]
Did we decide to hold off on an HTML version of the RTK PDF?

**Comment by birdsong** [comment]
Yes, holding off on the HTML - keeping it only in PDF format for now.

On Tue, Oct 28, 2014 at 8:56 PM, Gabriel Farrell notifications@github.com
wrote:

> Did we decide to hold off on an HTML version of the RTK PDF?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CityOfPhiladelphia/slash-data-temp/issues/12#issuecomment-60858047
> .

## 

Stacey Heather Mosley
C: 267-210-5246

**Comment by gsf** [comment]
Okay, good to know. Thanks!
