### ISSUE TITLE
Header lost its styling

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/slash-data#13]
I think when @gsf removed philagov.css the navbar header lost its styling.

![20141027230816999](https://cloud.githubusercontent.com/assets/761444/4801164/4a5a21f4-5e2e-11e4-8188-2e7696f98930.png)

vs

![20141027230830213](https://cloud.githubusercontent.com/assets/761444/4801165/4ec4205a-5e2e-11e4-952b-baba64e0b205.png)

**Comment by birdsong** [comment]
@timwis @majshehab informs me that this is a closed issue

**Comment by timwis** [comment]
Er, it appears to still be an issue. Am I missing something?

**Comment by gsf** [comment]
I did change the styling there a little. Are you saying the links should be whiter and lower in the nav bar?
