### ISSUE TITLE
Add feedback button

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/slash-data#15]
I'd like users to be able to let us know if we got something wrong on the census. Knack doesn't have that built-in, but I created a feedback form that optionally ties feedback to dataset(s). It's on /feedback. I had a floating "feedback" button implemented, but I'm not married to the look or position of that button - I just want to direct feedback to instead of people emailing or tweeting us.

**Comment by birdsong** [comment]
This needs to be added to the census page specifically

**Comment by gsf** [comment]
I was just thinking the same thing. Maybe a link in the intro text?

**Comment by birdsong** [comment]
Sure,I updated the copy.  Let me know what you think.

**Comment by gsf** [comment]
I made it so the link links to /feedback/. @timwis?

**Comment by timwis** [comment]
Can we add text by the "published" and "unpublished" tables saying something like "Have a question? Did you spot an error? Let us know!" and also to the "view details" page? With that, I think we can close this issue.

**Comment by birdsong** [comment]
Link is up on Census main page and the Census Details
