### ISSUE TITLE
Executive Order has  broken html and strange strings showing

### ISSUE THREAD

**Issue by birdsong** [CityOfPhiladelphia/slash-data#19]

**Comment by birdsong** [comment]
Search for:

"/li>"

and

â€™

**Comment by gsf** [comment]
Yeah, the executive order HTML is ugly and just requires some manual cleanup. I'll try to get to it but would be happy if someone else could jump on this. If no one gets to it could we link straight to the PDF in the meantime?

**Comment by timwis** [comment]
I fixed this in a commit last night - what happened to those changes?

**Comment by gsf** [comment]
The only commit I see around that file is 1fe77c4627f275b36dd3e941999198cb2459c0e9. Are there changes in your local copy that didn't get committed?
