### ISSUE TITLE
Change verbiage of Request widget

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/slash-data#22]
Please change "Not all data is currently open" to "Not all data is currently open data"

**Comment by gsf** [comment]
Will do but feel free to make modifications to [the index](../blob/gh-pages/index.html). Or anything else for that matter.

**Comment by gsf** [comment]
And totally understood about having a record via issues and not stepping on toes while a lot of cooks are in the kitchen but small tweaks like this I think we can each just do directly.
