### ISSUE TITLE
Census - Data Release Counts & Department Counts

### ISSUE THREAD

**Issue by birdsong** [CityOfPhiladelphia/slash-data#3]
Add a section beneath the introduction for the count of data sets and the department count totals to be side by side with their corresponding (existing charts) underneath them.

154

datasets
[quarterly chart: datasets by quarter]

by

35
departments
[pie chart: department totals]

**Comment by gsf** [comment]
How important is the "by" in the middle? It'll be a lot easier if it's just two columns. I'll do that for now so you can have a look.

**Comment by gsf** [comment]
I'm having some trouble figuring out how best to align the numbers with the charts, and thought it might be better to simply mention them in the copy instead. I like that this ties the text to the charts. What do you think?

**Comment by gsf** [comment]
I stuck the charts in Bootstrap panels, and I think they look okay. How do things look to you all now?

**Comment by gsf** [comment]
PS I'm feeling pretty :-1: about Knack, or at least the way we're using it. I'll try to write something up about it.

**Comment by birdsong** [comment]
The dept and data release totals should only reflect the totals for datasets where Published = Y

**Comment by gsf** [comment]
Looks like the numbers are still off.
