### ISSUE TITLE
Discuss link should point to embedded /discuss/ page

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/slash-data#5]
Unless the change was intentional?

**Comment by gsf** [comment]
It was, but I'm happy to weigh reasoning on both sides. I believe @atogle, @majshehab, and I thought the embedded Google Group didn't provide any functional or aesthetic benefit over the default interface, and could just confuse users who don't realize it's the Open Data Philly Google Group. We could be more explicit in the link (for example, it could instead read "ODP Discussion Group »").

**Comment by majshehab** [comment]
Yes, it didn't add much value being embedded as an iframe on a phila.gov page.

Changing the language "discussion board" to "Google Forum" would be helpful before shooting users out -- also opening in a new tab / _Blank as I mentioned in another ticket, since it is outside of our domain.

**Comment by timwis** [comment]
Okay. I suppose the point of it was to be able to tell people an easy URL to get there, like "phila.gov/data/census" instead of "google the opendataphilly google group" but "phila.gov/data" works too.

**Comment by birdsong** [comment]
@gsf - this needs to be re-opened

The Discuss page needs to go back to being the embedded version with URL phila.gov/data/discuss to coincide with content from the Strategic Plan document

Please also make sure there are breadcrumbs at the top of the page

**Comment by gsf** [comment]
How about a redirect from phila.gov/data/discuss to the Google Group page? I still think the embedded discussion looks cheesy.
