### ISSUE TITLE
Site footer

### ISSUE THREAD

**Issue by gsf** [CityOfPhiladelphia/slash-data#6]
I didn't do much yet for the footer and it feels unresolved. Suggestions appreciated.

**Comment by majshehab** [comment]
![screen shot 2014-10-27 at 10 19 21 am](https://cloud.githubusercontent.com/assets/4324930/4792144/e3be32b8-5de3-11e4-9925-f2bc4e33c006.png)

We could add the same footer that is currently on Phila.gov, since we are already using the (semi-useless) header.

**Comment by gsf** [comment]
Your thoughts, @timwis? Similar header as on the main site currently?

**Comment by timwis** [comment]
I can't think of anything we'd want on every page other than a way to provide feedback. It also looks weird when the /census/ page is loading and all you see is the footer. I think either we have no footer or we have the standard phila.gov one. Not a big deal IMO either way.

**Comment by gsf** [comment]
The weirdness on /census/ could be lessened by making it a [sticky footer](http://css-tricks.com/snippets/css/sticky-footer/), but I'd be quite satisfied if we just drop it entirely.

**Comment by atogle** [comment]
Closing.

**Comment by gsf** [comment]
What did we decide here? Are we just leaving the footer as is?

**Comment by atogle** [comment]
Footer removed and now pushed. My bad.

**Comment by gsf** [comment]
:+1:
