### ISSUE TITLE
Browse / Discuss / Request

### ISSUE THREAD

**Issue by majshehab** [CityOfPhiladelphia/slash-data#7]
*Link icons and headers to go to opendataphilly, discussionboard, procedure 
*Open in new tab / _blank for the first 2, since they're outside of phila.gov)
*Lesser important, but better for legibility, remove underlined hover-state of links at bottom and just make it a darker color for mouseover (this could go for all links on here)

**Comment by timwis** [comment]
1 & 2 appear to be done

**Comment by majshehab** [comment]
@timwis @gsf icons and titles still are not linked - though in the href below, they are opening in new tabs.

**Comment by gsf** [comment]
I must admit I'm not a fan of the header and icon as links. Reasons:
1. The existing links do the job just fine already.
2. Breaks parallel with the panels above.
3. Annoying when non-link parts of the page link to things.
4. If the link, header, and icon all link, it seems to me the entire panel should link, but then it's an even worse case of point 3.
5. Blue headers are ugly.

Just my thoughts! Happy to hear yours.
